version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-compression-backend
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000
    environment:
      NODE_ENV: production
    command: ["node", "start"]