version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-compression-backend
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000
    environment:
      NODE_ENV: production
    command: ["node", "app.js"]

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "80:80" # Exposes port 80 to the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mounts the Nginx configuration
